site_name: Myna Docs
nav:
  - Home: README.md
  - Quickstart:
    - quickstart/auth.md
    - quickstart/curl.md
    - quickstart/macros.md
    - quickstart/postman.md
    - quickstart/swagger.md
  - API:
    - apis/Apis/ASRApi.md
    - apis/Apis/DemosApi.md
    - apis/Apis/TTSApi.md
    - apis/Apis/VCApi.md
    - apis/Apis/LipSyncApi.md
  - OpenAPI:
    - openapi/index.md
theme: readthedocs
plugins:
   - swagger-ui-tag:
        background: "#ffffff"
        docExpansion: list
        tryItOutEnabled: false
