site_name: Myna Docs
nav:
  - Home: index.html
  - Quickstart:
    - quickstart/tts.md
    - quickstart/vc.md
    - quickstart/lipsync.md
    - quickstart/auth.md
  - Guides:
    - guides/swagger.md
    - guides/postman.md
    - guides/error_handling.md
    - guides/audio.md
    - guides/video.md
    - guides/macros.md
  - API:
    - apis/Apis/ASRApi.md
    - apis/Apis/DemosApi.md
    - apis/Apis/TTSApi.md
    - apis/Apis/VCApi.md
    - apis/Apis/LipSyncApi.md
  - OpenAPI:
    - openapi/index.md
theme: readthedocs
plugins:
   - swagger-ui-tag:
        background: "#ffffff"
        docExpansion: list
        tryItOutEnabled: false
