name: Build
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
  
jobs:
  openapi-compilation:
    name: 'Build from swagger'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2

      - name: 'Pull swagger'
        run: |
          wget https://gateway.neiro.ai/swagger/api.swagger.json

      - name: 'Build markdown api'
        run: |
          docker run --rm \
            -v $PWD:/local openapitools/openapi-generator-cli generate \
            -i /local/api.swagger.json \
            -g markdown \
            -o /local/out/md
      
      - name: 'Copy markdown output to site'
        run: |
          cp -r out/md/* gateway-docs/docs/apis

      - name: 'Install mkdocs'
        run: |
          pip install mkdocs

      - name: 'Install mkdocs swagger tag'
        run: |
          pip install mkdocs-swagger-ui-tag
      
      - name: 'Build site'
        run: |
          cd gateway-docs && mkdocs build
      
      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: gateway-docs/site          
